[package]
name = "recap-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.17", features = ["macros", "webhooks-axum"] }
log = "0.4"
pretty_env_logger = "0.5"
tokio = { version = "1.40", features = ["rt-multi-thread", "macros"] }
dotenv = "0.15"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-rustls", "migrate", "macros", "chrono"] }
serde_json = "1"
thiserror = "2.0.18"
serde = { version = "1", features = ["derive"] }
dptree = "0.5.1"
axum = { version = "0.8.9", default-features = false, features = ["tokio", "http1"] }
metrics = "0.24"
metrics-exporter-prometheus = "0.18.3"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
chrono = { version = "0.4.44", features = ["serde"] }
