apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: recap-bot
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: recap-bot
  namespaceSelector:
    matchNames:
      - recap-bot
  endpoints:
    - port: http
      path: /metrics
      interval: 15s